program: nlp_hw3_moe.py
method: bayes
metric:
  name: test/combined_score
  goal: maximize
parameters:
  adamw_lr:
    distribution: log_uniform_values
    min: 0.0014808525230129378
    max: 0.0016501427804313142
  adamw_weight_decay:
    distribution: uniform
    min: 0.04146738266733057
    max: 0.09822378523623015
  alpha:
    distribution: uniform
    min: 0.08149000264764056
    max: 0.2705866573633747
  muon_lr:
    distribution: log_uniform_values
    min: 0.0006079310635775991
    max: 0.0006854740007342842
  muon_weight_decay:
    distribution: uniform
    min: 0.026294799749205545
    max: 0.08762234790628556
  muon_momentum:
    distribution: uniform
    min: 0.9292980045320746
    max: 0.9412906001282134
  warmup_ratio:
    distribution: uniform
    min: 0.14456385892691304
    max: 0.22339677969386246
