program: nlp_hw3.py
method: bayes
metric:
  goal: maximize
  name: test/combined_score
parameters:
  adamw_weight_decay:
    max: 0.17614657709498868
    min: 0.00825024793945629
    distribution: log_uniform_values
  muon_weight_decay:
    max: 0.3731433032159963
    min: 0.011951480361223548
    distribution: log_uniform_values
  muon_momentum:
    max: 1.97989927870627
    min: 0.4510057962522432
    distribution: log_uniform_values
  batch_size:
    values: [16, 32, 64, 128]
  adamw_lr:
    max: 0.017531532762418506
    min: 0.000128722195367827
    distribution: log_uniform_values
  muon_lr:
    max: 0.01987019847083118
    min: 0.0006220199575832442
    distribution: log_uniform_values
  alpha:
    max: 0.9717699102082336
    min: 0.021026832269555013
    distribution: uniform