program: nlp_hw3.py
method: bayes
metric:
  name: test_combined_score
  goal: maximize
early_terminate:
  type: hyperband
  min_iter: 3
parameters:
  adamw_lr:
    distribution: log_uniform_values
    min: 0.00019714693273646872
    max: 0.00036613001793915623
  muon_lr:
    distribution: log_uniform_values
    min: 0.00042401849421038623
    max: 0.0007874629178192888
  weight_decay:
    distribution: log_uniform_values
    min: 0.00011137629117103125
    max: 0.000445505164684125
  dropout_rate:
    values:
    - 0.1
    - 0.15
  batch_size:
    values:
    - 128
    - 256
