program: nlp_hw3.py
method: bayes
metric:
  name: test_combined_score
  goal: maximize
parameters:
  adamw_lr:
    distribution: log_uniform_values
    min: 0.000144
    max: 0.000145
  muon_lr:
    distribution: log_uniform_values
    min: 0.00038632617798059867
    max: 0.000717462901963969
