program: nlp_hw3.py
method: bayes
metric:
  name: test_combined_score
  goal: maximize
parameters:
  adamw_lr: # Best: 0.00019801
    distribution: log_uniform_values
    min: 0.00003912
    max: 0.00009129
  muon_lr: # Best: 0.00068023
    distribution: log_uniform_values
    min: 0.00032093
    max: 0.00074884
  alpha: # Best: 0.1280
    distribution: uniform
    min: 0.0547
    max: 0.1276
  freeze_layers: # Best: 3
    values: [0, 1, 2, 3, 4, 5, 6, 7, 8]  # Top candidates
