program: nlp_hw2.py
method: bayes
metric:
  name: val_accuracy
  goal: maximize
parameters:
  adamw_lr:
    distribution: log_uniform_values
    min: 0.00015
    max: 0.002
  weight_decay:
    distribution: log_uniform_values
    min: 0.001
    max: 0.1
