program: nlp_hw2.py
method: bayes
metric:
  name: val_accuracy
  goal: maximize
early_terminate:
  type: hyperband
  min_iter: 2
parameters:
  lr:
    distribution: log_uniform_values
    min: 0.00085
    max: 0.0016
  weight_decay:
    distribution: log_uniform_values
    min: 0.0036
    max: 0.015
  momentum:
    distribution: log_uniform_values
    min: 0.94
    max: 0.999
  rnn_type:
    values: ['LSTM', 'GRU', 'RNN']