program: nlp_hw2.py
method: bayes
metric:
  name: val_accuracy
  goal: maximize
early_terminate:
  type: hyperband
  min_iter: 2
count: 15
parameters:
  batch_size:
    values: [128]
  embed_dim:
    values: [256, 512]
  hidden_dim:
    values: [256, 512]
  lr:
    distribution: log_uniform_values
    min: 0.0003
    max: 0.003
  grad_clip:
    values: [1]
  weight_decay:
    distribution: log_uniform_values
    min: 0.0001
    max: 0.01
  label_smoothing:
    values: [0.0, 0.1]
  rnn_type:
    values: ['LSTM', 'GRU', 'RNN']
