program: nlp_hw2.py
method: bayes
metric:
  name: val_accuracy
  goal: maximize
parameters:
  rnn_type:
    values: ['LSTM', 'GRU', 'RNN']
  train_mode:
    values: ['normal', '3digit_train_2digit_eval', 'noisy_20_train']
  optimizer:
    values: ['adamw', 'muon', 'lion', 'rmsprop']
