program: nlp_hw3.py
method: bayes
metric:
  name: test_combined_score
  goal: maximize
parameters:
  muon_lr:
    distribution: log_uniform_values
    min: 0.00005
    max: 0.001
  adamw_lr:
    distribution: log_uniform_values
    min: 0.00005
    max: 0.001
  weight_decay:
    distribution: log_uniform_values
    min: 1e-5
    max: 1e-3
  alpha:
    values: [0.5]
  dropout_rate:
    values: [0.05, 0.1, 0.15]