program: nlp_hw3.py
method: random
metric:
  name: test_combined_score
  goal: maximize
parameters:
  adamw_lr: # 0.000144535611723143
    distribution: log_uniform_values
    min: 0.00005
    max: 0.00025
  muon_lr: # 0.000577839942653345
    distribution: log_uniform_values
    min: 0.0001
    max: 0.0015
  adamw_weight_decay:
    distribution: uniform
    min: 0.005
    max: 0.015
  muon_weight_decay:
    distribution: uniform
    min: 0.005
    max: 0.015