program: nlp_hw3.py
method: bayes
metric:
  name: test_combined_score
  goal: maximize
parameters:
  adamw_lr: # 0.00014440709898314
    distribution: log_uniform_values
    min: 0.000144
    max: 0.000145
  muon_lr: # 0.000570533273915737
    distribution: log_uniform_values
    min: 0.000565
    max: 0.000575
  adamw_weight_decay: # 0.0358781442720464
    distribution: uniform
    min: 0.03
    max: 0.04
  muon_weight_decay: # 0.0336472354297785
    distribution: uniform
    min: 0.03
    max: 0.04
  muon_momentum:
    distribution: uniform
    min: 0.9
    max: 0.99