program: nlp_hw3.py
method: bayes
metric:
  name: test_combined_score
  goal: maximize
parameters:
  adamw_lr:
    distribution: log_uniform_values
    min: 0.00014
    max: 0.00015
  muon_lr:
    distribution: log_uniform_values
    min: 0.000565
    max: 0.000575
  weight_decay:
    distribution: log_uniform_values
    min: 0.00002
    max: 0.00003