program: nlp_hw3.py
method: bayes
metric:
  name: test_combined_score
  goal: maximize
parameters:
  adamw_lr:
    distribution: log_uniform_values
    min: 0.00012
    max: 0.00022
  muon_lr:
    distribution: log_uniform_values
    min: 0.0007
    max: 0.0009
  weight_decay:
    distribution: log_uniform_values
    min: 1.0e-5
    max: 1.0e-4
  warmup_ratio:
    distribution: uniform
    min: 0.0
    max: 0.2