program: nlp_hw3.py
method: random
metric:
  name: test_combined_score
  goal: maximize
parameters:
  adamw_lr:
    distribution: uniform
    min: 0.00001
    max: 0.01
  muon_lr:
    distribution: uniform
    min: 0.00005
    max: 0.05
  adamw_weight_decay:
    distribution: uniform
    min: 0.0
    max: 0.1
  muon_weight_decay:
    distribution: uniform
    min: 0.0
    max: 0.1
  alpha:
    distribution: uniform
    min: 0.0
    max: 0.5
  batch_size:
    values: [32, 64, 128, 256, 512, 1024]