program: nlp_hw3.py
method: bayes
metric:
  name: test_combined_score
  goal: maximize
parameters:
  adamw_lr:
    distribution: log_uniform_values
    min: 0.00015
    max: 0.00045
  muon_lr:
    distribution: log_uniform_values
    min: 0.01
    max: 0.03
  adamw_weight_decay:
    distribution: uniform
    min: 0.005
    max: 0.015
  muon_weight_decay:
    distribution: uniform
    min: 0.005
    max: 0.015