program: nlp_hw3.py
method: bayes
metric:
  name: test_combined_score
  goal: maximize
parameters:
  adamw_lr:
    distribution: log_uniform_values
    min: 0.0008595449749773559
    max: 0.002336485486224231
  adamw_weight_decay:
    distribution: log_uniform_values
    min: 0.03036625366641276
    max: 0.08254403553978766
  alpha:
    distribution: log_uniform_values
    min: 0.15786174872914904
    max: 0.42911272297921366
  muon_lr:
    distribution: log_uniform_values
    min: 0.0001976716373270689
    max: 0.0005373272197479181
  muon_weight_decay:
    distribution: log_uniform_values
    min: 0.029381489191254915
    max: 0.07986716816165408
