program: nlp_hw2.py
method: bayes
metric:
  name: val_accuracy
  goal: maximize
early_terminate:
  type: hyperband
  min_iter: 3
parameters:
  lr:
    distribution: log_uniform_values
    min: 0.0008
    max: 0.0015
  weight_decay:
    distribution: log_uniform_values
    min: 0.0025
    max: 0.01
  rnn_type:
    values: ['LSTM', 'GRU', 'RNN']
