program: nlp_hw2.py
method: bayes
metric:
  name: val_accuracy
  goal: maximize
early_terminate:
  type: hyperband
  min_iter: 3
parameters:
  lr:
    distribution: log_uniform_values
    min: 0.000806008214923142
    max: 0.0014968723991429782
  weight_decay:
    distribution: log_uniform_values
    min: 0.0027012706900452895
    max: 0.010805082760181158
  rnn_type:
    values:
    - GRU
    - LSTM
