program: nlp_hw3_moe.py
method: random
metric:
  name: test/combined_score
  goal: maximize
parameters:
  adamw_lr:
    distribution: uniform
    min: 0.0005836557602121656
    max: 0.009041314422502073
  adamw_weight_decay:
    distribution: uniform
    min: 0.011120530827615008
    max: 0.09009925975608893
  alpha:
    distribution: uniform
    min: 0.03886645051446547
    max: 0.48805536730150956
  muon_lr:
    distribution: uniform
    min: 0.00014156850155393332
    max: 0.004806633419373154
  muon_weight_decay:
    distribution: uniform
    min: 0.05123461511694752
    max: 0.18204534123945576
  muon_momentum:
    distribution: uniform
    min: 0.8981027662917295
    max: 0.9920297706214157
  batch_size:
    values: [16, 64, 128]
