program: nlp_hw2.py
method: bayes
metric:
  name: val_accuracy
  goal: maximize
early_terminate:
  type: hyperband
  min_iter: 3
parameters:
  rnn_type:
    values:
    - LSTM
    - GRU
  batch_size:
    values:
    - 128
    - 256
