program: nlp_hw3.py
method: bayes
metric:
  name: test_combined_score
  goal: maximize
early_terminate:
  type: hyperband
  min_iter: 3
parameters:
  adamw_lr:
    distribution: log_uniform_values
    min: 0.00016891001401084997
    max: 0.00031369002602015
  muon_lr:
    distribution: log_uniform_values
    min: 0.00032992359610126
    max: 0.00061271524990234
  weight_decay:
    distribution: log_uniform_values
    min: 9.239984817815e-05
    max: 0.0003695993927126
  dropout_rate:
    values:
    - 0.15
    - 0.05
  batch_size:
    values:
    - 128
    - 256
