name: nlp
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - anyio=4.10.0=py312h06a4308_0
  - aom=3.6.0=h6a678d5_0
  - argon2-cffi=21.3.0=pyhd3eb1b0_0
  - argon2-cffi-bindings=25.1.0=py312hee96239_0
  - asttokens=3.0.0=py312h06a4308_0
  - async-lru=2.0.4=py312h06a4308_0
  - babel=2.16.0=py312h06a4308_0
  - beautifulsoup4=4.13.5=py312h06a4308_0
  - blas=1.0=mkl
  - bleach=6.2.0=py312h06a4308_0
  - bottleneck=1.4.2=py312ha883a20_0
  - brotli-python=1.0.9=py312h6a678d5_9
  - brotlicffi=1.0.9.2=py312h6a678d5_1
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2025.9.9=h06a4308_0
  - cairo=1.18.4=h44eff21_0
  - certifi=2025.8.3=py312h06a4308_0
  - cffi=1.17.1=py312h1fdaa30_1
  - click=8.2.1=py312h06a4308_0
  - comm=0.2.1=py312h06a4308_0
  - dav1d=1.2.1=h5eee18b_0
  - debugpy=1.8.16=py312hbdd6827_0
  - decorator=5.2.1=py312h06a4308_0
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - executing=2.2.1=py312h06a4308_0
  - expat=2.7.1=h6a678d5_0
  - fontconfig=2.15.0=h2c49b7f_0
  - fonttools=4.59.2=py312hee96239_0
  - freetype=2.13.3=h4a9f257_0
  - fribidi=1.0.10=h7b6447c_0
  - graphite2=1.3.14=h295c915_1
  - h11=0.16.0=py312h06a4308_0
  - harfbuzz=10.2.0=hdfddeaa_1
  - httpcore=1.0.9=py312h06a4308_0
  - httpx=0.28.1=py312h06a4308_0
  - icu=73.1=h6a678d5_0
  - intel-openmp=2023.0.0=h9e868ea_25371
  - ipykernel=6.30.1=py312h06a4308_0
  - ipython=9.5.0=py312h06a4308_0
  - ipython_pygments_lexers=1.1.1=py312h06a4308_0
  - ipywidgets=8.1.5=py312h06a4308_0
  - jedi=0.19.2=py312h06a4308_0
  - jinja2=3.1.6=py312h06a4308_0
  - joblib=1.5.2=py312h06a4308_0
  - jpeg=9f=h5ce9db8_0
  - json5=0.9.25=py312h06a4308_0
  - jsonschema=4.25.0=py312h06a4308_0
  - jsonschema-specifications=2023.7.1=py312h06a4308_0
  - jupyter=1.1.1=py312h06a4308_0
  - jupyter-lsp=2.2.5=py312h06a4308_0
  - jupyter_client=8.6.3=py312h06a4308_0
  - jupyter_console=6.6.3=py312h06a4308_1
  - jupyter_core=5.8.1=py312h06a4308_0
  - jupyter_events=0.12.0=py312h06a4308_0
  - jupyter_server=2.16.0=py312h06a4308_0
  - jupyter_server_terminals=0.5.3=py312h06a4308_0
  - jupyterlab=4.4.7=py312h06a4308_0
  - jupyterlab_pygments=0.3.0=py312h06a4308_0
  - jupyterlab_server=2.27.3=py312h06a4308_0
  - jupyterlab_widgets=3.0.15=py312h06a4308_0
  - lcms2=2.16=h92b89f2_1
  - ld_impl_linux-64=2.40=h12ee557_0
  - lerc=4.0.0=h6a678d5_0
  - libavif=1.1.1=h5eee18b_0
  - libdeflate=1.22=h5eee18b_0
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libglib=2.84.2=h37c7471_0
  - libgomp=11.2.0=h1234567_1
  - libiconv=1.16=h5eee18b_3
  - libpng=1.6.39=h5eee18b_0
  - libsodium=1.0.20=heac8642_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtiff=4.7.0=hde9077f_0
  - libuuid=1.41.5=h5eee18b_0
  - libwebp-base=1.3.2=h5eee18b_1
  - libxcb=1.17.0=h9b100fa_0
  - libxml2=2.13.8=hfdd30dd_0
  - libzlib=1.3.1=hb25bd0a_0
  - lz4-c=1.9.4=h6a678d5_1
  - markupsafe=3.0.2=py312h5eee18b_0
  - matplotlib-base=3.10.6=py312h71dd3da_0
  - matplotlib-inline=0.1.7=py312h06a4308_0
  - mistune=3.1.2=py312h06a4308_0
  - mkl=2023.1.0=h213fc3f_46344
  - mkl-service=2.4.0=py312h5eee18b_2
  - mkl_fft=1.3.11=py312h5eee18b_0
  - mkl_random=1.2.8=py312h526ad5a_0
  - nbclient=0.10.2=py312h06a4308_0
  - nbconvert=7.16.6=py312h06a4308_0
  - nbconvert-core=7.16.6=py312h06a4308_0
  - nbconvert-pandoc=7.16.6=py312h06a4308_0
  - nbformat=5.10.4=py312h06a4308_0
  - ncurses=6.5=h7934f7d_0
  - nest-asyncio=1.6.0=py312h06a4308_0
  - nltk=3.9.1=py312h06a4308_0
  - notebook=7.4.5=py312h06a4308_0
  - notebook-shim=0.2.4=py312h06a4308_0
  - numexpr=2.11.0=py312hf4471f9_0
  - openjpeg=2.5.2=h0d4d230_1
  - openssl=3.0.18=hd6dcaed_0
  - overrides=7.4.0=py312h06a4308_0
  - packaging=25.0=py312h06a4308_0
  - pandas=2.3.2=py312h277b779_0
  - pandoc=3.8=h06a4308_0
  - pandocfilters=1.5.1=py312h06a4308_0
  - parso=0.8.4=py312h06a4308_0
  - pcre2=10.42=hebb0a14_1
  - pexpect=4.9.0=py312h06a4308_0
  - pillow=11.3.0=py312hb1c3d2d_0
  - pip=25.2=pyhc872135_0
  - pixman=0.46.4=h7934f7d_0
  - platformdirs=4.3.7=py312h06a4308_0
  - prometheus_client=0.21.1=py312h06a4308_0
  - prompt-toolkit=3.0.43=py312h06a4308_0
  - prompt_toolkit=3.0.43=hd3eb1b0_0
  - psutil=7.0.0=py312hee96239_0
  - pthread-stubs=0.3=h0ce48e5_1
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pure_eval=0.2.3=py312h06a4308_0
  - pycparser=2.23=py312h06a4308_0
  - pygments=2.19.1=py312h06a4308_0
  - pysocks=1.7.1=py312h06a4308_0
  - python=3.12.11=h22baa00_0
  - python-dateutil=2.9.0post0=py312h06a4308_2
  - python-fastjsonschema=2.20.0=py312h06a4308_0
  - python-json-logger=3.2.1=py312h06a4308_0
  - python-tzdata=2025.2=pyhd3eb1b0_0
  - pytz=2025.2=py312h06a4308_0
  - pyzmq=27.1.0=py312hcf8288c_0
  - qtconsole=5.7.0=py312h06a4308_0
  - qtpy=2.4.3=py312h06a4308_0
  - readline=8.3=hc2a1206_0
  - referencing=0.30.2=py312h06a4308_0
  - regex=2025.9.1=py312hee96239_0
  - requests=2.32.5=py312h06a4308_0
  - rfc3339-validator=0.1.4=py312h06a4308_0
  - rfc3986-validator=0.1.1=py312h06a4308_0
  - rpds-py=0.22.3=py312h4aa5aa6_0
  - seaborn=0.13.2=py312h06a4308_3
  - send2trash=1.8.2=py312h06a4308_1
  - setuptools=78.1.1=py312h06a4308_0
  - six=1.17.0=py312h06a4308_0
  - sniffio=1.3.0=py312h06a4308_0
  - sqlite=3.50.2=hb25bd0a_1
  - stack_data=0.6.3=py312h06a4308_0
  - tbb=2021.8.0=hdb19cb5_0
  - terminado=0.18.1=py312h06a4308_0
  - tinycss2=1.4.0=py312h06a4308_0
  - tk=8.6.15=h54e0aa7_0
  - tornado=6.5.1=py312h5eee18b_0
  - tqdm=4.67.1=py312he106c6f_0
  - traitlets=5.14.3=py312h06a4308_0
  - typing-extensions=4.15.0=py312h06a4308_0
  - typing_extensions=4.15.0=py312h06a4308_0
  - tzdata=2025b=h04d1e81_0
  - unicodedata2=15.1.0=py312h5eee18b_1
  - urllib3=2.5.0=py312h06a4308_0
  - wcwidth=0.2.13=py312h06a4308_0
  - webencodings=0.5.1=py312h06a4308_2
  - websocket-client=1.8.0=py312h06a4308_0
  - wheel=0.45.1=py312h06a4308_0
  - widgetsnbextension=4.0.13=py312h06a4308_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-libxext=1.3.6=h9b100fa_0
  - xorg-libxrender=0.9.12=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - yaml=0.2.5=h7b6447c_0
  - zeromq=4.3.5=hb0a5e54_1
  - zlib=1.3.1=hb25bd0a_0
  - zstd=1.5.7=h11fc155_0
  - pip:
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.12.15
      - aiosignal==1.4.0
      - annotated-types==0.7.0
      - attrs==25.3.0
      - chardet==5.2.0
      - charset-normalizer==3.4.3
      - contourpy==1.3.3
      - cycler==0.12.1
      - datasets==4.1.1
      - dill==0.4.0
      - filelock==3.19.1
      - frozenlist==1.7.0
      - fsspec==2025.9.0
      - gdown==5.2.0
      - gensim==4.3.3
      - gitdb==4.0.12
      - gitpython==3.1.45
      - gunzip==0.1.10
      - head==1.0.0
      - hf-xet==1.1.10
      - huggingface-hub==0.35.1
      - idna==3.10
      - kiwisolver==1.4.9
      - lion-pytorch==0.2.3
      - microapp==0.3.15
      - mpmath==1.3.0
      - multidict==6.6.4
      - multiprocess==0.70.16
      - muon-optimizer==0.1.0
      - networkx==3.5
      - numpy==1.26.4
      - nvidia-cublas-cu12==12.8.4.1
      - nvidia-cuda-cupti-cu12==12.8.90
      - nvidia-cuda-nvrtc-cu12==12.8.93
      - nvidia-cuda-runtime-cu12==12.8.90
      - nvidia-cudnn-cu12==9.10.2.21
      - nvidia-cufft-cu12==11.3.3.83
      - nvidia-cufile-cu12==1.13.1.3
      - nvidia-curand-cu12==10.3.9.90
      - nvidia-cusolver-cu12==11.7.3.90
      - nvidia-cusparse-cu12==12.5.8.93
      - nvidia-cusparselt-cu12==0.7.1
      - nvidia-nccl-cu12==2.27.3
      - nvidia-nvjitlink-cu12==12.8.93
      - nvidia-nvtx-cu12==12.8.90
      - opencc==1.1.9
      - propcache==0.3.2
      - protobuf==6.32.1
      - pyarrow==21.0.0
      - pydantic==2.12.0
      - pydantic-core==2.41.1
      - pyparsing==3.2.3
      - pyyaml==6.0.3
      - scikit-learn==1.7.2
      - scipy==1.13.1
      - sentry-sdk==2.41.0
      - smart-open==7.3.1
      - smmap==5.0.2
      - soupsieve==2.8
      - sympy==1.14.0
      - threadpoolctl==3.6.0
      - torch==2.8.0
      - torchvision==0.23.0
      - triton==3.4.0
      - typing-inspection==0.4.2
      - wandb==0.22.2
      - wrapt==1.17.3
      - xxhash==3.5.0
      - yarl==1.20.1
prefix: /home/kris/miniconda3/envs/nlp
