program: nlp_hw3.py
method: bayes
metric:
  name: test_combined_score
  goal: maximize
early_terminate:
  type: hyperband
  min_iter: 3
parameters:
  adamw_lr:
    distribution: log_uniform_values
    min: 0.00016394063623258997
    max: 0.00030446118157481
  muon_lr:
    distribution: log_uniform_values
    min: 0.00039028209168429827
    max: 0.0007248095988422683
  weight_decay:
    distribution: log_uniform_values
    min: 6.356516741334166e-05
    max: 0.00025426066965336663
  dropout_rate:
    values:
    - 0.05
    - 0.15
  batch_size:
    values:
    - 128
    - 256
